name: Create a comment on new issues

permissions:
  issues: write
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            REMINDER
            PR reviewed and approved by at least one teammate
            Updated documentation if needed
            No secrets or sensitive info in commits
          reactions: '+1'
