---
name: Lint

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@v8.1.0 # x-release-please-version
        env:
          FILTER_REGEX_INCLUDE: src/.*.(go|mod|sum)$
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GO: true
          VALIDATE_GO_MOD: true
          # Disable other linters we don't need
          VALIDATE_YAML: false
          VALIDATE_JSON: false
          VALIDATE_MARKDOWN: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_BASH: false
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}